databases.tutorial.datasources.json.ds_moody.ROUTE.AUTHENTICATION.GRANT=CLIENT_CREDENTIALS_GRANT
databases.tutorial.datasources.json.ds_moody.ROUTE.HTTP.ACCESSTOKEN=In03jutPx+2Ad70mcoJHLupCtOyNxDnxazoQ6Xl12hJK0VEUsryH6a3Go6KSzDOV1QJzZNM2OvNh6eAwhwsJpNKIPBM4Yt+xZ6qbF/ytTxi97269U9Rx5LnhNMzSJ43k1aOCqImaywjEQINiYM4JC9x5FoClBMh2e479+lrNLx8\=
databases.tutorial.datasources.json.ds_moody.ROUTE.HTTP.ACCESSTOKEN.ENCRYPTED=ENCRYPTED
databases.tutorial.datasources.json.ds_moody.ROUTE.HTTP.ACCESSTOKENEXPIRESIN=3600
databases.tutorial.datasources.json.ds_moody.ROUTE.HTTP.CLIENTIDENTIFIER=B871E13A-D63F-4420-B6B6-6935A238CE6A
databases.tutorial.datasources.json.ds_moody.ROUTE.HTTP.CLIENTSECRET=Ti6998AO3a9I3vp7Dni1Ddso9IJQnsWs8cT1ilrcEbbkhmSTl768BnvIg2MXyQVTHTPlsdbNIMDJLPJSrYKEhdxu2Qw3mgFEzQKYOH5MQzSDqbJT5DZ4q15j3tP3DiTB8v/lG8MD8vgGr4NjQI6tC6+SlFNNbTU0aj2QrSaYOko\=
databases.tutorial.datasources.json.ds_moody.ROUTE.HTTP.CLIENTSECRET.ENCRYPTED=ENCRYPTED
databases.tutorial.datasources.json.ds_moody.ROUTE.HTTP.REQUESTSIGNINGMETHOD=HEADER
databases.tutorial.datasources.json.ds_moody.ROUTE.HTTP.TOKENENDPOINTURL=https\://api.economy.com/data/v1/oauth2/token
databases.tutorial.datasources.json.ds_moody.ROUTE.HTTP.URL=https\://api.economy.com/data/v1/series/?m\=FGDPL$Q.ISAU&freq\=QUARTERLY
