databases.tutorial.datasources.json.ds_rest_denodo_element_search.ROUTE.HTTP.PASSWORD=S539MKwN7ZdSEyRqWRP46N+viWNCHmhvlMCDqBl/uAUW1+tApFv3ZHT/2+2rWEGmtmxuSM3gU0qZ9E/heUa071ppx82g12TMUkmkDTKEFQyDk0+KyUFDYbqsJ8kWKbe6
databases.tutorial.datasources.json.ds_rest_denodo_element_search.ROUTE.HTTP.PASSWORD.ENCRYPTED=ENCRYPTED
databases.tutorial.datasources.json.ds_rest_denodo_element_search.ROUTE.HTTP.URL=http\://localhost\:9090/denodo-data-catalog/public/api/catalog-search/elements?nameFilter\=@searchVal
databases.tutorial.datasources.json.ds_rest_denodo_element_search.ROUTE.HTTP.USER=admin
